baseURL = 'https://positivepeng.github.io/'
languageCode = 'en-us'
title = 'Phil的碎碎念'
theme = 'PaperMod'

# 启用标签和分类
[taxonomies]
  tag = 'tags'
  category = 'categories'

# 菜单配置
[[menu.main]]
  name = '搜索'
  url = '/search/'
  weight = 1

[[menu.main]]
  name = '标签'
  url = '/tags/'
  weight = 2

[[menu.main]]
  name = '分类'
  url = '/categories/'
  weight = 3

[[menu.main]]
  name = '存档'
  url = '/archives/'
  weight = 4

[[menu.main]]
  name = '关于'
  url = '/about/'
  weight = 5

# 搜索配置
[outputs]
  home = ["HTML", "RSS", "JSON"]

# 首页信息
[params]
 comments = true

[params.assets]
  favicon = "favicon.svg"
  favicon16x16 = "favicon.svg"
  favicon32x32 = "favicon.svg"
  apple_touch_icon = "favicon.svg"
  safari_pinned_tab = "favicon.svg"
  theme_color = "#2e2e33"

[params.homeInfoParams]
  Title = "Phil的碎碎念"
  Content = """
  INTJ | 长期主义 | 推荐算法工程师 ｜ 满仓居士
  """
  AlignSocialIconsTo = "left"

# 社交账号图标
[[params.socialIcons]]
  name = "github"
  url = "https://github.com/positivepeng"

[[params.socialIcons]]
  name = "zhihu"
  url = "https://www.zhihu.com/people/jie-sheng-hao"

# 评论系统（Giscus）

[params.giscus]
 repo = "positivepeng/positivepeng.github.io"
 repoId = "R_kgDORyDUAA"
 category = "Announcements"
 categoryId = "DIC_kwDORyDUAM4C5e2_"
 mapping = "pathname"
 strict = "0"
 reactionsEnabled = "1"
 emitMetadata = "0"
 inputPosition = "bottom"
 theme = "preferred_color_scheme"
 lang = "zh-CN"
